/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ResortAdministration;

/**
 *
 * @author USER
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton3 = new com.k33ptoo.components.KButton();
        kButton4 = new com.k33ptoo.components.KButton();
        kButton5 = new com.k33ptoo.components.KButton();
        kButton6 = new com.k33ptoo.components.KButton();
        kButton7 = new com.k33ptoo.components.KButton();
        kButton8 = new com.k33ptoo.components.KButton();
        kButton9 = new com.k33ptoo.components.KButton();
        kButton10 = new com.k33ptoo.components.KButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(244, 236, 127));
        kGradientPanel1.setkGradientFocus(600);
        kGradientPanel1.setkStartColor(new java.awt.Color(134, 183, 248));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(1280, 730));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton2.setText("BACK");
        kButton2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        kButton2.setkBackGroundColor(new java.awt.Color(42, 45, 53));
        kButton2.setkBorderRadius(20);
        kButton2.setkEndColor(new java.awt.Color(89, 255, 120));
        kButton2.setkForeGround(new java.awt.Color(51, 51, 0));
        kButton2.setkHoverColor(new java.awt.Color(255, 255, 102));
        kButton2.setkHoverEndColor(new java.awt.Color(255, 241, 192));
        kButton2.setkHoverForeGround(new java.awt.Color(0, 102, 51));
        kButton2.setkHoverStartColor(new java.awt.Color(255, 255, 102));
        kButton2.setkPressedColor(new java.awt.Color(0, 204, 204));
        kButton2.setkStartColor(new java.awt.Color(240, 241, 192));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 50));

        kButton3.setText("COTTAGE BOOKINGS");
        kButton3.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        kButton3.setkBackGroundColor(new java.awt.Color(42, 45, 53));
        kButton3.setkBorderRadius(20);
        kButton3.setkEndColor(new java.awt.Color(89, 255, 120));
        kButton3.setkForeGround(new java.awt.Color(51, 51, 0));
        kButton3.setkHoverColor(new java.awt.Color(255, 255, 102));
        kButton3.setkHoverEndColor(new java.awt.Color(255, 241, 192));
        kButton3.setkHoverForeGround(new java.awt.Color(0, 102, 51));
        kButton3.setkHoverStartColor(new java.awt.Color(255, 255, 102));
        kButton3.setkPressedColor(new java.awt.Color(0, 204, 204));
        kButton3.setkStartColor(new java.awt.Color(240, 241, 192));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 680, 70));

        kButton4.setText("VENUE BOOKINGS");
        kButton4.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        kButton4.setkBackGroundColor(new java.awt.Color(42, 45, 53));
        kButton4.setkBorderRadius(20);
        kButton4.setkEndColor(new java.awt.Color(89, 255, 120));
        kButton4.setkForeGround(new java.awt.Color(51, 51, 0));
        kButton4.setkHoverColor(new java.awt.Color(255, 255, 102));
        kButton4.setkHoverEndColor(new java.awt.Color(255, 241, 192));
        kButton4.setkHoverForeGround(new java.awt.Color(0, 102, 51));
        kButton4.setkHoverStartColor(new java.awt.Color(255, 255, 102));
        kButton4.setkPressedColor(new java.awt.Color(0, 204, 204));
        kButton4.setkStartColor(new java.awt.Color(240, 241, 192));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 680, 70));

        kButton5.setText("CUSTOMER REGISTRATIONS");
        kButton5.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        kButton5.setkBackGroundColor(new java.awt.Color(42, 45, 53));
        kButton5.setkBorderRadius(20);
        kButton5.setkEndColor(new java.awt.Color(89, 255, 120));
        kButton5.setkForeGround(new java.awt.Color(51, 51, 0));
        kButton5.setkHoverColor(new java.awt.Color(255, 255, 102));
        kButton5.setkHoverEndColor(new java.awt.Color(255, 241, 192));
        kButton5.setkHoverForeGround(new java.awt.Color(0, 102, 51));
        kButton5.setkHoverStartColor(new java.awt.Color(255, 255, 102));
        kButton5.setkPressedColor(new java.awt.Color(0, 204, 204));
        kButton5.setkStartColor(new java.awt.Color(240, 241, 192));
        kButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton5ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 680, 70));

        kButton6.setText("REQUESTED GYM PASSES");
        kButton6.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        kButton6.setkBackGroundColor(new java.awt.Color(42, 45, 53));
        kButton6.setkBorderRadius(20);
        kButton6.setkEndColor(new java.awt.Color(89, 255, 120));
        kButton6.setkForeGround(new java.awt.Color(51, 51, 0));
        kButton6.setkHoverColor(new java.awt.Color(255, 255, 102));
        kButton6.setkHoverEndColor(new java.awt.Color(255, 241, 192));
        kButton6.setkHoverForeGround(new java.awt.Color(0, 102, 51));
        kButton6.setkHoverStartColor(new java.awt.Color(255, 255, 102));
        kButton6.setkPressedColor(new java.awt.Color(0, 204, 204));
        kButton6.setkStartColor(new java.awt.Color(240, 241, 192));
        kButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton6ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 680, 70));

        kButton7.setText("WITHDRAWN MONEY");
        kButton7.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        kButton7.setkBackGroundColor(new java.awt.Color(42, 45, 53));
        kButton7.setkBorderRadius(20);
        kButton7.setkEndColor(new java.awt.Color(89, 255, 120));
        kButton7.setkForeGround(new java.awt.Color(51, 51, 0));
        kButton7.setkHoverColor(new java.awt.Color(255, 255, 102));
        kButton7.setkHoverEndColor(new java.awt.Color(255, 241, 192));
        kButton7.setkHoverForeGround(new java.awt.Color(0, 102, 51));
        kButton7.setkHoverStartColor(new java.awt.Color(255, 255, 102));
        kButton7.setkPressedColor(new java.awt.Color(0, 204, 204));
        kButton7.setkStartColor(new java.awt.Color(240, 241, 192));
        kButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton7ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 680, 70));

        kButton8.setText("CHECKOUTS");
        kButton8.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        kButton8.setkBackGroundColor(new java.awt.Color(42, 45, 53));
        kButton8.setkBorderRadius(20);
        kButton8.setkEndColor(new java.awt.Color(89, 255, 120));
        kButton8.setkForeGround(new java.awt.Color(51, 51, 0));
        kButton8.setkHoverColor(new java.awt.Color(255, 255, 102));
        kButton8.setkHoverEndColor(new java.awt.Color(255, 241, 192));
        kButton8.setkHoverForeGround(new java.awt.Color(0, 102, 51));
        kButton8.setkHoverStartColor(new java.awt.Color(255, 255, 102));
        kButton8.setkPressedColor(new java.awt.Color(0, 204, 204));
        kButton8.setkStartColor(new java.awt.Color(240, 241, 192));
        kButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton8ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 610, 680, 70));

        kButton9.setText("REQUESTED HEALTH SUPPORT");
        kButton9.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        kButton9.setkBackGroundColor(new java.awt.Color(42, 45, 53));
        kButton9.setkBorderRadius(20);
        kButton9.setkEndColor(new java.awt.Color(89, 255, 120));
        kButton9.setkForeGround(new java.awt.Color(51, 51, 0));
        kButton9.setkHoverColor(new java.awt.Color(255, 255, 102));
        kButton9.setkHoverEndColor(new java.awt.Color(255, 241, 192));
        kButton9.setkHoverForeGround(new java.awt.Color(0, 102, 51));
        kButton9.setkHoverStartColor(new java.awt.Color(255, 255, 102));
        kButton9.setkPressedColor(new java.awt.Color(0, 204, 204));
        kButton9.setkStartColor(new java.awt.Color(240, 241, 192));
        kButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton9ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, 680, 70));

        kButton10.setText("TOUR BOOKINGS");
        kButton10.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        kButton10.setkBackGroundColor(new java.awt.Color(42, 45, 53));
        kButton10.setkBorderRadius(20);
        kButton10.setkEndColor(new java.awt.Color(89, 255, 120));
        kButton10.setkForeGround(new java.awt.Color(51, 51, 0));
        kButton10.setkHoverColor(new java.awt.Color(255, 255, 102));
        kButton10.setkHoverEndColor(new java.awt.Color(255, 241, 192));
        kButton10.setkHoverForeGround(new java.awt.Color(0, 102, 51));
        kButton10.setkHoverStartColor(new java.awt.Color(255, 255, 102));
        kButton10.setkPressedColor(new java.awt.Color(0, 204, 204));
        kButton10.setkStartColor(new java.awt.Color(240, 241, 192));
        kButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton10ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 680, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ResortAdministration/Images/adminHome.png"))); // NOI18N
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 512, 512));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ADMIN CONTROL PANEL");
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        // TODO add your handling code here:
        CottageBookings cottageBookings=new CottageBookings();
        cottageBookings.show();
        dispose();
    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
        Welcome welcome=new Welcome();
        welcome.show();
        dispose();
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        // TODO add your handling code here:
        VenueBookings venueBookings=new VenueBookings();
        venueBookings.show();
        dispose();
    }//GEN-LAST:event_kButton4ActionPerformed

    private void kButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton5ActionPerformed
        // TODO add your handling code here:
        CustomerRegistrations customerRegistrations=new CustomerRegistrations();
        customerRegistrations.show();
        dispose();
    }//GEN-LAST:event_kButton5ActionPerformed

    private void kButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton6ActionPerformed
        // TODO add your handling code here:\
        GymPasses gymPasses=new GymPasses();
        gymPasses.show();
        dispose();
    }//GEN-LAST:event_kButton6ActionPerformed

    private void kButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton7ActionPerformed
        // TODO add your handling code here:
        MoneyWithdraws moneyWithdraws=new MoneyWithdraws();
        moneyWithdraws.show();
        dispose();
    }//GEN-LAST:event_kButton7ActionPerformed

    private void kButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton8ActionPerformed
        // TODO add your handling code here:\
        Checkouts checkouts=new Checkouts();
        checkouts.show();
        dispose();
    }//GEN-LAST:event_kButton8ActionPerformed

    private void kButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton9ActionPerformed
        // TODO add your handling code here:
        HealthSupports healthSupports=new HealthSupports();
        healthSupports.show();
        dispose();
    }//GEN-LAST:event_kButton9ActionPerformed

    private void kButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton10ActionPerformed
        // TODO add your handling code here:
        TourBookings tourBookings=new TourBookings();
        tourBookings.show();
        dispose();
    }//GEN-LAST:event_kButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private com.k33ptoo.components.KButton kButton10;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KButton kButton5;
    private com.k33ptoo.components.KButton kButton6;
    private com.k33ptoo.components.KButton kButton7;
    private com.k33ptoo.components.KButton kButton8;
    private com.k33ptoo.components.KButton kButton9;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
