/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ResortAdministration;

import javax.swing.JOptionPane;


/**
 *
 * @author USER
 */
public class GymPass extends javax.swing.JFrame {

    /**
     * Creates new form GymPass
     */
    public GymPass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton3 = new com.k33ptoo.components.KButton();
        jLabel9 = new javax.swing.JLabel();
        shour = new javax.swing.JTextField();
        jRadioButton4 = new javax.swing.JRadioButton();
        sminute = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        day = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        month = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        eminute = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        year = new javax.swing.JTextField();
        ehour = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(51, 51, 255));
        kGradientPanel1.setkGradientFocus(600);
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 102, 255));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(1280, 730));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton2.setText("BACK");
        kButton2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        kButton2.setkBackGroundColor(new java.awt.Color(42, 45, 53));
        kButton2.setkBorderRadius(20);
        kButton2.setkEndColor(new java.awt.Color(89, 255, 120));
        kButton2.setkForeGround(new java.awt.Color(51, 51, 0));
        kButton2.setkHoverColor(new java.awt.Color(255, 255, 102));
        kButton2.setkHoverEndColor(new java.awt.Color(255, 241, 192));
        kButton2.setkHoverForeGround(new java.awt.Color(0, 102, 51));
        kButton2.setkHoverStartColor(new java.awt.Color(255, 255, 102));
        kButton2.setkPressedColor(new java.awt.Color(0, 204, 204));
        kButton2.setkStartColor(new java.awt.Color(240, 241, 192));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 30, 120, 50));

        kButton3.setText("ENTER");
        kButton3.setFont(new java.awt.Font("Consolas", 1, 40)); // NOI18N
        kButton3.setkBackGroundColor(new java.awt.Color(42, 45, 53));
        kButton3.setkBorderRadius(20);
        kButton3.setkEndColor(new java.awt.Color(89, 255, 120));
        kButton3.setkForeGround(new java.awt.Color(51, 51, 0));
        kButton3.setkHoverColor(new java.awt.Color(255, 255, 102));
        kButton3.setkHoverEndColor(new java.awt.Color(255, 241, 192));
        kButton3.setkHoverForeGround(new java.awt.Color(0, 102, 51));
        kButton3.setkHoverStartColor(new java.awt.Color(255, 255, 102));
        kButton3.setkPressedColor(new java.awt.Color(0, 204, 204));
        kButton3.setkStartColor(new java.awt.Color(240, 241, 192));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, 290, 90));

        jLabel9.setFont(new java.awt.Font("Bodoni MT", 1, 75)); // NOI18N
        jLabel9.setText("GET GYM PASS");
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, 70));

        shour.setFont(new java.awt.Font("sansserif", 0, 30)); // NOI18N
        shour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shourActionPerformed(evt);
            }
        });
        kGradientPanel1.add(shour, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 80, 65));

        jRadioButton4.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jRadioButton4.setText("AM");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, -1, -1));

        sminute.setFont(new java.awt.Font("sansserif", 0, 30)); // NOI18N
        sminute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sminuteActionPerformed(evt);
            }
        });
        kGradientPanel1.add(sminute, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 80, 65));

        jLabel14.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        jLabel14.setText("ENDING       : ");
        kGradientPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, 113));

        day.setFont(new java.awt.Font("sansserif", 0, 30)); // NOI18N
        day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayActionPerformed(evt);
            }
        });
        kGradientPanel1.add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 80, 65));

        jLabel12.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        jLabel12.setText("DATE           :");
        kGradientPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, 113));

        jRadioButton3.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jRadioButton3.setText("PM");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, -1, -1));

        jLabel13.setFont(new java.awt.Font("Bodoni MT", 1, 48)); // NOI18N
        jLabel13.setText(":");
        kGradientPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 20, -1));

        month.setFont(new java.awt.Font("sansserif", 0, 30)); // NOI18N
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });
        kGradientPanel1.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 80, 65));

        jLabel10.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        jLabel10.setText("STARTING   : ");
        kGradientPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, 113));

        jLabel11.setFont(new java.awt.Font("Bodoni MT", 1, 48)); // NOI18N
        jLabel11.setText("/");
        kGradientPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 20, -1));

        eminute.setFont(new java.awt.Font("sansserif", 0, 30)); // NOI18N
        eminute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eminuteActionPerformed(evt);
            }
        });
        kGradientPanel1.add(eminute, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 80, 65));

        jLabel7.setFont(new java.awt.Font("Bodoni MT", 1, 48)); // NOI18N
        jLabel7.setText(":");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 20, -1));

        jLabel15.setFont(new java.awt.Font("Bodoni MT", 1, 48)); // NOI18N
        jLabel15.setText("/");
        kGradientPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 20, -1));

        jRadioButton2.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jRadioButton2.setText("AM");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, -1, -1));

        year.setFont(new java.awt.Font("sansserif", 0, 30)); // NOI18N
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });
        kGradientPanel1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 150, 65));

        ehour.setFont(new java.awt.Font("sansserif", 0, 30)); // NOI18N
        ehour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ehourActionPerformed(evt);
            }
        });
        kGradientPanel1.add(ehour, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 80, 65));

        jRadioButton1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jRadioButton1.setText("PM");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.show();
        dispose();
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        // TODO add your handling code here:
        int sshour = Integer.parseInt(shour.getText());
        int eehour = Integer.parseInt(ehour.getText());
        if (jRadioButton1.isSelected()) {
            sshour = sshour + 12;
        }
        if (jRadioButton3.isSelected()) {
            eehour = eehour + 12;
        }
        Welcome.jdbc.gymPass(Integer.parseInt(year.getText()) - 1900, Integer.parseInt(month.getText()) - 1,
                Integer.parseInt(day.getText()), sshour,
                Integer.parseInt(sminute.getText()), eehour, Integer.parseInt(eminute.getText()));
        JOptionPane.showMessageDialog(this, "You have got the gym Pass!");
        Home home = new Home();
        home.show();
        dispose();
    }//GEN-LAST:event_kButton3ActionPerformed

    private void shourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shourActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void sminuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sminuteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sminuteActionPerformed

    private void dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthActionPerformed

    private void eminuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eminuteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eminuteActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void ehourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ehourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ehourActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GymPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GymPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GymPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GymPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GymPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField day;
    private javax.swing.JTextField ehour;
    private javax.swing.JTextField eminute;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField month;
    private javax.swing.JTextField shour;
    private javax.swing.JTextField sminute;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
